### ISSUE TITLE
When running "grunt serve", some script resources could not be found because of case-sensitive file system

### ISSUE THREAD

**Issue by antetna** [Tivix/angular-django-registration-auth#10]
(index):71 GET http://127.0.0.1:9000/scripts/controllers/passwordReset.js 
(index):72 GET http://127.0.0.1:9000/scripts/controllers/passwordResetConfirm.js 
(index):74 GET http://127.0.0.1:9000/scripts/controllers/verifyEmail.js 
(index):76 GET http://127.0.0.1:9000/scripts/controllers/userProfile.js 
(index):77 GET http://127.0.0.1:9000/scripts/controllers/passwordChange.js 

example:
**passwordreset.js**  <> **passwordReset.js**

**Comment by petershafer** [comment]
Sorry about that, @antetna.  OS X is too forgiving of casing for me.  Thanks for letting us know.
