### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by Madsn** [Tivix/angular-django-registration-auth#9]
I'm having a strange issue, most likely just some incorrect setup.

Initially I was having issues getting it working with gulp as my task runner, where using grunt works just fine. But if I run `grunt build` and then serve up the content from the `dist` folder, I get a 401 error when trying to log in. Server response is `detail: "Invalid token"`.

When loading the main page and attempting to log in, my console contains the following:
```
GET http://127.0.0.1:8000/rest-auth/user/ 403 (FORBIDDEN) angular.js:8380
error syncing with: //127.0.0.1:8000/rest-auth/user/ 9d7fcc59.scripts.js:1
POST http://127.0.0.1:8000/rest-auth/login/ 401 (UNAUTHORIZED) angular.js:8380
error syncing with: //127.0.0.1:8000/rest-auth/login/ 9d7fcc59.scripts.js:1
```
Which is pretty much the same thing I'm getting when serving the content via gulp, except the line numbers are of more use since the js isn't minified:
```
GET http://127.0.0.1:8000/rest-auth/user/ 403 (FORBIDDEN) angular.js:8561
error syncing with: http://127.0.0.1:8000/rest-auth/user/ djangoAuth.js:43
POST http://127.0.0.1:8000/rest-auth/login/ 401 (UNAUTHORIZED) 127.0.0.1:8000/rest-auth/login/:1
error syncing with: http://127.0.0.1:8000/rest-auth/login/ djangoAuth.js:43
```

Any help would be very much appreciated.

**Comment by adimux** [comment]
Did you incorporate it in your project who is using a version of angularjs 1.4+  ?
If so $cookies must be used with getter and setter [angularjs $cookies docs](https://docs.angularjs.org/api/ngCookies/service/$cookies)
So you'll have to edit scripts/services/djangoAuth.js to correct it.

**Comment by tab-cmd** [comment]
@Madsn were you able to resolve this issue?

**Comment by Madsn** [comment]
Sorry I never managed to get it working, and I'm no longer using that setup. Probably safe to close this now.
